language: python
env:
  - CHANNEL_SECRET=secret CHANNEL_ACCESS_TOKEN=token
cache: pip
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"
script:
  - "python runtests.py"
